Unemployment Analysis

In [35]:
#importing the necessary libraries
import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
import matplotlib.pyplot as plt

In [36]:
#Loading the dataset
data = pd.read_csv('unemployment_data.csv')
data

,Region,Date,Frequency,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),Region.1,longitude,latitude
0,Andhra Pradesh,31-01-2020,M,5.48,16635535,41.02,South,15.9129,79.740
1,Andhra Pradesh,29-02-2020,M,5.83,16545652,40.90,South,15.9129,79.740
2,Andhra Pradesh,31-03-2020,M,5.79,15881197,39.18,South,15.9129,79.740
3,Andhra Pradesh,30-04-2020,M,20.51,11336911,33.10,South,15.9129,79.740
4,Andhra Pradesh,31-05-2020,M,17.43,12988845,36.46,South,15.9129,79.740
...,...,...,...,...,...,...,...,...,...
262,West Bengal,30-06-2020,M,7.29,30726310,40.39,East,22.9868,87.855
263,West Bengal,31-07-2020,M,6.83,35372506,46.17,East,22.9868,87.855
264,West Bengal,31-08-2020,M,14.87,33298644,47.48,East,22.9868,87.855
265,West Bengal,30-09-2020,M,9.35,35707239,47.73,East,22.9868,87.855
266,West Bengal,31-10-2020,M,9.98,33962549,45.63,East,22.9868,87.855

Data preprocessing

In [37]:
data.columns

Index(['Region', ' Date', ' Frequency', ' Estimated Unemployment Rate (%)',
       ' Estimated Employed', ' Estimated Labour Participation Rate (%)',
       'Region.1', 'longitude', 'latitude'],
      dtype='object')

In [38]:
data.isnull().sum()

Region                                      0
 Date                                       0
 Frequency                                  0
 Estimated Unemployment Rate (%)            0
 Estimated Employed                         0
 Estimated Labour Participation Rate (%)    0
Region.1                                    0
longitude                                   0
latitude                                    0
dtype: int64

In [39]:
data.describe()

,Estimated Unemployment Rate (%),Estimated Employed,Estimated Labour Participation Rate (%),longitude,latitude
count,267.000000,2.670000e+02,267.000000,267.000000,267.000000
mean,12.236929,1.396211e+07,41.681573,22.826048,80.532425
std,10.803283,1.336632e+07,7.845419,6.270731,5.831738
min,0.500000,1.175420e+05,16.770000,10.850500,71.192400
25%,4.845000,2.838930e+06,37.265000,18.112400,76.085600
50%,9.650000,9.732417e+06,40.390000,23.610200,79.019300
75%,16.755000,2.187869e+07,44.055000,27.278400,85.279900
max,75.850000,5.943376e+07,69.690000,33.778200,92.937600

In [40]:
#df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
# data[' Date'] = data[' Date'].str[:-3]
# data[' Date'] = pd.to_datetime(data[' Date'], format=' %d-%m-%y')

In [41]:
x = data[' Date'].values.reshape(-1,1)
y = data[' Estimated Unemployment Rate (%)'].values

In [42]:
print(x)

[[' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']
 [' 31-01-2020']
 [' 29-02-2020']
 [' 31-03-2020']
 [' 30-04-2020']
 [' 31-05-2020']
 [' 30-06-2020']
 [' 31-07-2020']
 [' 31-08-2020']
 [' 30-09-2020']
 [' 31-10-2020']]

In [43]:
y

array([ 5.48,  5.83,  5.79, 20.51, 17.43,  3.31,  8.34,  6.96,  6.4 ,
        6.59,  4.66,  4.41,  4.77, 11.06,  9.55,  0.6 ,  3.77,  5.53,
        1.19,  3.02, 10.61, 10.29, 15.43, 46.64, 45.96, 17.82, 12.79,
       13.44, 11.91,  9.82,  9.65,  8.38,  7.54,  3.41, 10.5 , 14.23,
       10.27,  5.63,  1.96,  6.62, 22.23, 14.84, 17.04, 16.68, 42.27,
       18.19, 20.3 , 13.79, 12.53,  6.27,  8.89,  2.81,  5.25, 13.31,
       21.25,  9.96, 17.07, 16.21, 15.38, 11.54,  5.54,  6.38,  6.66,
       18.71, 12.11,  3.2 ,  1.84,  1.87,  3.42,  4.03, 20.34, 25.77,
       25.05, 43.22, 29.02, 26.7 , 24.18, 33.5 , 19.68, 27.31, 16.83,
       16.84, 18.76,  2.2 , 26.95, 13.47, 24.31, 15.79, 12.04, 13.46,
       21.08, 20.78, 15.5 , 18.74, 17.92, 10.88, 11.09, 16.17, 16.14,
       10.61, 11.85,  8.23, 47.09, 59.23, 20.95,  7.63,  9.76,  8.24,
       11.8 ,  2.86,  3.61,  3.46, 29.84, 19.97,  8.44,  4.01,  0.5 ,
        2.41,  1.58,  5.31,  7.6 ,  8.99, 16.99, 17.88,  9.71,  7.09,
       10.98,  5.91,  3.88,  4.11,  4.57,  2.22, 12.36, 21.98,  6.48,
        5.08,  4.7 ,  3.91,  3.13,  4.95,  4.69,  5.79, 20.9 , 15.46,
        9.23,  3.89,  6.23,  4.55,  4.1 ,  1.66,  3.59,  1.58, 10.03,
        5.92,  1.15,  2.1 ,  3.74,  4.29,  4.6 ,  1.9 ,  3.12, 13.08,
       23.76, 11.41,  3.77,  1.88,  1.42,  2.1 ,  2.18,  0.58,  1.76,
        1.2 , 75.85, 58.19,  4.24, 15.47,  5.05, 10.9 ,  6.18, 11.11,
       10.97, 10.32,  2.86, 28.33, 16.55,  9.19, 10.99,  9.61,  9.88,
       10.97, 15.16, 11.9 , 17.7 , 15.74, 14.39, 15.81, 17.51, 15.35,
       24.15, 23.57,  2.28, 24.51,  4.46,  4.45, 12.49,  5.7 ,  0.88,
        1.57,  2.09,  6.4 , 49.83, 33.16, 12.2 ,  6.81,  2.65,  5.  ,
        2.16,  5.49,  8.29,  5.77,  6.25, 14.7 , 10.55,  5.36,  5.79,
        3.27,  2.86, 32.67, 28.4 , 29.95, 41.23, 21.51, 21.71, 18.24,
       27.92, 17.35, 11.57,  7.58,  8.98, 10.11, 21.54, 20.41,  9.47,
        5.56,  5.79,  4.18,  3.75,  5.49,  4.99, 19.85,  6.48,  8.01,
        8.61, 12.38, 14.26, 22.26,  9.23,  6.94,  4.92,  6.92, 17.41,
       17.41,  7.29,  6.83, 14.87,  9.35,  9.98])

In [44]:
#splitting the dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [45]:
#fitting the model
# model = RandomForestRegressor(n_estimators=100, random_state=42)
# model.fit(x_train, y_train)